In [40]:
# lets pip install a cool package!
#!pip install ipyvolume

# then lets import
import ipyvolume
#%matplotlib inline

In [41]:
# make sure you unpack this dataset!
import yt
import numpy as np

ds = yt.load('/Users/jillnaiman1/Downloads/enzo_tiny_cosmology/DD0027/DD0027')

yt : [INFO     ] 2019-04-18 14:33:44,506 Parameters: current_time              = 135.816623852
yt : [INFO     ] 2019-04-18 14:33:44,508 Parameters: domain_dimensions         = [32 32 32]
yt : [INFO     ] 2019-04-18 14:33:44,510 Parameters: domain_left_edge          = [0. 0. 0.]
yt : [INFO     ] 2019-04-18 14:33:44,511 Parameters: domain_right_edge         = [1. 1. 1.]
yt : [INFO     ] 2019-04-18 14:33:44,513 Parameters: cosmological_simulation   = 1
yt : [INFO     ] 2019-04-18 14:33:44,514 Parameters: current_redshift          = 0.587036270836
yt : [INFO     ] 2019-04-18 14:33:44,515 Parameters: omega_lambda              = 0.727
yt : [INFO     ] 2019-04-18 14:33:44,517 Parameters: omega_matter              = 0.273
yt : [INFO     ] 2019-04-18 14:33:44,518 Parameters: hubble_constant           = 0.702


In [42]:
# what are the variables "native" to this dataset?
ds.field_list

Parsing Hierarchy : 100%|██████████| 147/147 [00:00<00:00, 30875.99it/s]
yt : [INFO     ] 2019-04-18 14:33:44,552 Gathering a field list (this may take a moment.)


[('all', 'creation_time'),
 ('all', 'dynamical_time'),
 ('all', 'metallicity_fraction'),
 ('all', 'particle_index'),
 ('all', 'particle_mass'),
 ('all', 'particle_position_x'),
 ('all', 'particle_position_y'),
 ('all', 'particle_position_z'),
 ('all', 'particle_type'),
 ('all', 'particle_velocity_x'),
 ('all', 'particle_velocity_y'),
 ('all', 'particle_velocity_z'),
 ('enzo', 'Dark_Matter_Density'),
 ('enzo', 'Density'),
 ('enzo', 'Metal_Density'),
 ('enzo', 'Temperature'),
 ('enzo', 'TotalEnergy'),
 ('enzo', 'x-velocity'),
 ('enzo', 'y-velocity'),
 ('enzo', 'z-velocity'),
 ('io', 'creation_time'),
 ('io', 'dynamical_time'),
 ('io', 'metallicity_fraction'),
 ('io', 'particle_index'),
 ('io', 'particle_mass'),
 ('io', 'particle_position_x'),
 ('io', 'particle_position_y'),
 ('io', 'particle_position_z'),
 ('io', 'particle_type'),
 ('io', 'particle_velocity_x'),
 ('io', 'particle_velocity_y'),
 ('io', 'particle_velocity_z')]

In [43]:
# what are some of the things yt derives for us?
ds.derived_field_list

[('all', 'age'),
 ('all', 'creation_time'),
 ('all', 'dynamical_time'),
 ('all', 'mesh_id'),
 ('all', 'metallicity_fraction'),
 ('all', 'particle_angular_momentum'),
 ('all', 'particle_angular_momentum_magnitude'),
 ('all', 'particle_angular_momentum_x'),
 ('all', 'particle_angular_momentum_y'),
 ('all', 'particle_angular_momentum_z'),
 ('all', 'particle_cylindrical_velocity_theta'),
 ('all', 'particle_cylindrical_velocity_z'),
 ('all', 'particle_index'),
 ('all', 'particle_mass'),
 ('all', 'particle_ones'),
 ('all', 'particle_position'),
 ('all', 'particle_position_cylindrical_radius'),
 ('all', 'particle_position_cylindrical_theta'),
 ('all', 'particle_position_cylindrical_z'),
 ('all', 'particle_position_relative'),
 ('all', 'particle_position_relative_x'),
 ('all', 'particle_position_relative_y'),
 ('all', 'particle_position_relative_z'),
 ('all', 'particle_position_spherical_phi'),
 ('all', 'particle_position_spherical_radius'),
 ('all', 'particle_position_spherical_theta'),
 ('al

In [44]:
dd = ds.covering_grid(level=0,left_edge=[0,0,0], dims=ds.domain_dimensions)

In [45]:
# lets plot the gas density in 3d
density3d = dd[('gas','density')]
density3d = density3d.to_ndarray()
density3d, density3d.shape

(array([[[2.73092641e-30, 6.28805059e-30, 1.30674741e-30, ...,
          5.75500268e-31, 9.82307647e-31, 1.41425735e-30],
         [3.17354542e-30, 3.27317585e-30, 1.10296421e-30, ...,
          3.85565883e-31, 8.46580953e-31, 1.70783525e-30],
         [5.10386495e-30, 3.59456746e-30, 1.37130327e-30, ...,
          3.13745021e-31, 6.38847311e-31, 2.14241863e-30],
         ...,
         [3.17513739e-30, 4.42313048e-30, 5.71145360e-30, ...,
          8.21290856e-31, 1.76240382e-30, 2.86507904e-30],
         [2.35399740e-30, 5.87084604e-30, 3.28918899e-30, ...,
          1.25263141e-30, 1.50989565e-30, 1.67185853e-30],
         [2.28786130e-30, 7.99848429e-30, 2.00351987e-30, ...,
          9.83644885e-31, 1.15519299e-30, 1.23121399e-30]],
 
        [[2.24293057e-30, 4.66026462e-30, 1.44234839e-30, ...,
          6.57645659e-31, 1.15727556e-30, 1.58270920e-30],
         [1.72271650e-30, 1.77799149e-30, 9.49941267e-31, ...,
          4.33010862e-31, 1.04342608e-30, 1.65651341e-30],
       

In [46]:
# sense these are low levels, lets take the log
density3d = np.log10(density3d)
density3d

array([[[-29.56369   , -29.20148397, -29.88380835, ..., -30.23995447,
         -30.00775248, -29.84947155],
        [-29.49845528, -29.48503066, -29.95743858, ..., -30.4139014 ,
         -30.07233151, -29.76755403],
        [-29.29210083, -29.44435336, -29.86286649, ..., -30.50342316,
         -30.19460293, -29.66909566],
        ...,
        [-29.49823748, -29.35427025, -29.24325335, ..., -30.08550301,
         -29.75389457, -29.54286339],
        [-29.62819402, -29.23129931, -29.48291117, ..., -29.9021767 ,
         -29.82105307, -29.77680047],
        [-29.64057031, -29.0969923 , -29.69820635, ..., -30.00716166,
         -29.93734545, -29.90966646]],

       [[-29.64918417, -29.33158942, -29.84092982, ..., -30.18200804,
         -29.93656322, -29.80059887],
        [-29.76378619, -29.75007032, -30.02230325, ..., -30.36350121,
         -29.98153831, -29.78080504],
        [-29.75633781, -29.72894211, -29.96583467, ..., -30.47701338,
         -30.11089239, -29.78477733],
        ...,


In [47]:
# finally, lets renormalize to the max & min ranges:
density3d = (density3d - np.min(density3d))/(np.max(density3d)-np.min(density3d))
density3d

array([[[0.40820806, 0.50892206, 0.31919685, ..., 0.22016785,
         0.28473329, 0.32874444],
        [0.42634704, 0.43007986, 0.29872343, ..., 0.17180066,
         0.26677663, 0.3515222 ],
        [0.48372539, 0.44139047, 0.32501988, ..., 0.14690849,
         0.23277818, 0.37889926],
        ...,
        [0.42640761, 0.46643873, 0.49730778, ..., 0.26311419,
         0.35532031, 0.41399905],
        [0.39027225, 0.50063169, 0.4306692 , ..., 0.3140894 ,
         0.33664641, 0.34895116],
        [0.38683094, 0.53797672, 0.37080482, ..., 0.28489757,
         0.30431047, 0.31200681]],

       [[0.38443579, 0.4727453 , 0.33111953, ..., 0.23628028,
         0.30452798, 0.34233384],
        [0.35256988, 0.35638367, 0.28068734, ..., 0.18581479,
         0.29202233, 0.34783766],
        [0.35464095, 0.36225852, 0.29638884, ..., 0.15425192,
         0.2560545 , 0.34673314],
        ...,
        [0.43458279, 0.44934072, 0.50157522, ..., 0.24545026,
         0.32522116, 0.40110489],
        [0.4

In [52]:
#from IPython.display import IFrame
#IFrame(src='http://localhost:8888/notebooks/prep_week13.ipynb',width=1000,height=500)

ipyvolume.figure(width=800, height=500)

# now lets plot!
ipyvolume.quickvolshow(density3d, level=[0.1, 0.5, 0.75], opacity=0.03, level_width=0.1)
# not: you might have to restart your browser after you pip install

# note the 3 levels & opacities refer to the RGB levels
#  levels are telling you where each color will "hit" in your density
#  So, for example, if I want RED to hit at 1/2 of my density level
#   (recall we have renormalized our density box)
# then I can set the "levels" of the first abar to 0.5
#  Then I can set the opacity levels for the other colors way down & the RED one way up

VkJveChjaGlsZHJlbj0oVkJveChjaGlsZHJlbj0oSEJveChjaGlsZHJlbj0oTGFiZWwodmFsdWU9dSdsZXZlbHM6JyksIEZsb2F0U2xpZGVyKHZhbHVlPTAuMSwgbWF4PTEuMCwgc3RlcD0wLjDigKY=


In [51]:
# there are also the "opacity" and "brightness" to play with

In [72]:
# since we also have velocity vectors for the gas in this sim
# lets plot them with arrows so we can see how they are moving!

# first we'll grab the x/y/z positions
#x = dd[('gas','x')].to_ndarray()
#y = dd[('gas','y')].to_ndarray()
#z = dd[('gas','z')].to_ndarray()

# now we want lists so we'll grab data another way
dd2 = ds.all_data()
x = dd2[('gas','x')].to_ndarray()
y = dd2[('gas','y')].to_ndarray()
z = dd2[('gas','z')].to_ndarray()

# lets normalize them all to the max
#x = (x-x.min())/(x.max()-x.min())
#y = (y-y.min())/(y.max()-y.min())
#z = (z-z.min())/(z.max()-z.min())


In [73]:
# then lets grab vel x/y/z
vx = dd2[('gas','velocity_x')].to_ndarray()
vy = dd2[('gas','velocity_y')].to_ndarray()
vz = dd2[('gas','velocity_z')].to_ndarray()

In [74]:
# lets plot!
ipyvolume.quickquiver(x,y,z, vx,vy,vz, size=5)

VkJveChjaGlsZHJlbj0oRmlndXJlKGNhbWVyYT1QZXJzcGVjdGl2ZUNhbWVyYShmb3Y9NDYuMCwgcG9zaXRpb249KDAuMCwgMC4wLCAyLjApLCBxdWF0ZXJuaW9uPSgwLjAsIDAuMCwgMC4wLCDigKY=


In [97]:
# obviously, those are too many arrows!

# lets only look at the dense gas:
density2 = dd2[('gas','density')].to_ndarray()

density2 = (density2-density2.min())/(density2.max()-density2.min())

# at > 0.005 -> you can see clumps of gas where stuff is falling in
# at > 0.0005 you can see some streams of gas
# > 0.00005 you see lots of stream structures
# 0.000005 you see structure, but its hard to disentangle
#  I feel like 0.00002 or 0.00001 is a good bet
mask = density2 > 0.00002


In [104]:


ipyvolume.quickquiver(x[mask],y[mask],z[mask], vx[mask],vy[mask],vz[mask], size=5)

# we can also do some stylistic thigns like:
ipyvolume.style.use("dark") # looks better
ipyvolume.show()


VkJveChjaGlsZHJlbj0oRmlndXJlKGNhbWVyYT1QZXJzcGVjdGl2ZUNhbWVyYShmb3Y9NDYuMCwgcG9zaXRpb249KDAuMCwgMC4wLCAyLjApLCBxdWF0ZXJuaW9uPSgwLjAsIDAuMCwgMC4wLCDigKY=
