# Activity #1: MarketMap
* another way to visualize mappable data

## 1.a : explore the dataset

In [31]:
# our usual stuff
%matplotlib inline
import pandas as pd
import numpy as np

In [2]:
#!pip install xlrd # JPN, might have to run this

# note: this is quering from the web!  How neat is that??
df = pd.read_excel('https://query.data.world/s/ivl45pdpubos6jpsii3djsjwm2pcjv', skiprows=5)
# the above might take a while to load all the data

In [3]:
# what is in this dataframe? lets take a look at the top
df.head()
# this dataset is called: "Surgery Charges Across the U.S."
#  and its just showing us how much different procedures 
#  cost from different hospitals

DRG Definition  Provider Id  \
0  001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...        10033   
1  001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...        30103   
2  001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...        50108   
3  001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...        50262   
4  001 - HEART TRANSPLANT OR IMPLANT OF HEART ASS...        50441   

                          Provider Name   Provider Street Address  \
0        UNIVERSITY OF ALABAMA HOSPITAL     619 SOUTH 19TH STREET   
1                  MAYO CLINIC HOSPITAL  5777 EAST MAYO BOULEVARD   
2               SUTTER GENERAL HOSPITAL             2801 L STREET   
3  RONALD REAGAN U C L A MEDICAL CENTER        757 WESTWOOD PLAZA   
4                     STANFORD HOSPITAL         300 PASTEUR DRIVE   

  Provider City Provider State  Provider Zip Code  \
0    BIRMINGHAM             AL              35233   
1       PHOENIX             AZ              85054   
2    SACRAMENTO             CA              95816   
3   LOS ANGELES             CA              90095   
4      STANFORD             CA              94305   

  Hospital Referral Region (HRR) Description  Total Discharges  \
0                            AL - Birmingham                13   
1                               AZ - Phoenix                20   
2                            CA - Sacramento                25   
3                           CA - Los Angeles                14   
4                      CA - San Mateo County                23   

   Average Covered Charges  Average Total Payments  Average Medicare Payments  
0             1.172866e+06           251876.307692              244457.923077  
1             4.375313e+05           240422.800000              133509.550000  
2             8.156741e+05           233197.480000              221681.800000  
3             1.499044e+06           415968.785714              366608.928571  
4             2.238699e+06           420865.478261              403453.652174

In [4]:
# what kinds of data are we working with?
df.dtypes

DRG Definition                                 object
Provider Id                                     int64
Provider Name                                  object
Provider Street Address                        object
Provider City                                  object
Provider State                                 object
Provider Zip Code                               int64
Hospital Referral Region (HRR) Description     object
Total Discharges                                int64
Average Covered Charges                       float64
Average Total Payments                        float64
Average Medicare Payments                     float64
dtype: object

In [5]:
# lets look at some summary data
# recall: this is like R's "summary" function
df.describe()
# so, things like the mean zipcode aren't
#  meaningful, same thing with provider ID
#  But certainly looking at the average
#  total payments, discharges, might 
#  be useful

Provider Id  Provider Zip Code  Total Discharges  \
count  202656.000000      202656.000000     202656.000000   
mean   255322.552749       47029.141698         36.011196   
std    150834.203550       27792.935433         48.864835   
min     10001.000000        1040.000000         11.000000   
25%    110082.000000       25301.000000         14.000000   
50%    240093.000000       43701.000000         22.000000   
75%    380014.000000       71603.000000         39.000000   
max    670088.000000       99801.000000       3855.000000   

       Average Covered Charges  Average Total Payments  \
count             2.026560e+05           202656.000000   
mean              5.258934e+04            13168.560144   
std               6.244522e+04            13772.839671   
min               1.367652e+03             2320.482759   
25%               2.094930e+04             6258.925806   
50%               3.463380e+04             9180.169753   
75%               6.076193e+04            14631.466690   
max               2.238699e+06           434396.000000   

       Average Medicare Payments  
count              202656.000000  
mean                11218.465217  
std                 12279.103622  
min                  1329.909091  
25%                  5011.979167  
50%                  7714.654762  
75%                 12472.680288  
max                403453.652174

In [6]:
# lets look at how many seperate types of surgery are 
#  represented in this dataset:
df["DRG Definition"].unique().size

564

In [7]:
# what about how many provider (hospital) names?
df["Provider Name"].unique().size

3151

In [8]:
# how many states are represented
df["Provider State"].unique().size

51

In [9]:
# what are the state codes?
df["Provider State"].unique()

array([u'AL', u'AZ', u'CA', u'CT', u'DC', u'FL', u'GA', u'IL', u'IN',
       u'KY', u'LA', u'MA', u'MI', u'MN', u'MO', u'NE', u'NJ', u'NY',
       u'NC', u'OH', u'OK', u'PA', u'SC', u'TN', u'TX', u'VA', u'WA',
       u'WI', u'AK', u'AR', u'CO', u'DE', u'ID', u'IA', u'KS', u'ME',
       u'MD', u'MS', u'NV', u'NH', u'NM', u'ND', u'OR', u'RI', u'UT',
       u'VT', u'WV', u'HI', u'SD', u'MT', u'WY'], dtype=object)

In [15]:
# lets figure out  what the most common surgeries are via how 
#  many many folks are discharged after each type of surgery
# (1)
most_common = df.groupby("DRG Definition")["Total Discharges"].sum()
most_common

# (2) but lets sort by the largest on top
most_common = df.groupby("DRG Definition")["Total Discharges"].sum().sort_values(ascending=False)
most_common

# (3) lets look at only the top 5, for fun
most_common[:5]

# (4) or we can only look at the names of the top 5:
most_common[:5].index.values

array([u'470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT OF LOWER EXTREMITY W/O MCC',
       u'871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HOURS W MCC',
       u'291 - HEART FAILURE & SHOCK W MCC',
       u'292 - HEART FAILURE & SHOCK W CC',
       u'392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISORDERS W/O MCC'],
      dtype=object)

## 1.b: formatting data for MarketMap
* here we are going to practice doing some fancy things to clean this data
* this will be good practice for when you run into other datasets "in the wild"

In [26]:
# (1) lets create a little table of total discharges for
#  each type of surgery & state
total_discharges = df.groupby(["DRG Definition", "Provider State"])["Total Discharges"].sum()
total_discharges

# (2) the above is not intuative, lets prettify it
total_discharges = df.groupby(["DRG Definition", "Provider State"])["Total Discharges"].sum().unstack()
total_discharges

Provider State                                        AK     AL     AR     AZ  \
DRG Definition                                                                  
001 - HEART TRANSPLANT OR IMPLANT OF HEART ASSI...   NaN   13.0    NaN   20.0   
002 - HEART TRANSPLANT OR IMPLANT OF HEART ASSI...   NaN    NaN    NaN    NaN   
003 - ECMO OR TRACH W MV 96+ HRS OR PDX EXC FAC...  12.0  237.0  128.0  200.0   
004 - TRACH W MV 96+ HRS OR PDX EXC FACE, MOUTH...  11.0  257.0  129.0  127.0   
005 - LIVER TRANSPLANT W MCC OR INTESTINAL TRAN...   NaN   16.0    NaN   17.0   
006 - LIVER TRANSPLANT W/O MCC                       NaN    NaN    NaN    NaN   
007 - LUNG TRANSPLANT                                NaN    NaN    NaN   22.0   
008 - SIMULTANEOUS PANCREAS/KIDNEY TRANSPLANT        NaN    NaN    NaN    NaN   
011 - TRACHEOSTOMY FOR FACE,MOUTH & NECK DIAGNO...   NaN   15.0    NaN   13.0   
012 - TRACHEOSTOMY FOR FACE,MOUTH & NECK DIAGNO...   NaN   47.0   14.0   12.0   
013 - TRACHEOSTOMY FOR FACE,MOUTH & NECK DIAGNO...   NaN   13.0   12.0    NaN   
014 - ALLOGENEIC BONE MARROW TRANSPLANT              NaN   13.0    NaN   18.0   
016 - AUTOLOGOUS BONE MARROW TRANSPLANT W CC/MCC     NaN   25.0   28.0   49.0   
017 - AUTOLOGOUS BONE MARROW TRANSPLANT W/O CC/MCC   NaN   11.0    NaN   15.0   
020 - INTRACRANIAL VASCULAR PROCEDURES W PDX HE...   NaN   14.0   15.0    NaN   
023 - CRANIO W MAJOR DEV IMPL/ACUTE COMPLEX CNS...   NaN   56.0   35.0   60.0   
024 - CRANIO W MAJOR DEV IMPL/ACUTE COMPLEX CNS...   NaN    NaN    NaN   32.0   
025 - CRANIOTOMY & ENDOVASCULAR INTRACRANIAL PR...   NaN  249.0  227.0  435.0   
026 - CRANIOTOMY & ENDOVASCULAR INTRACRANIAL PR...   NaN   88.0   62.0  164.0   
027 - CRANIOTOMY & ENDOVASCULAR INTRACRANIAL PR...   NaN  130.0   83.0  206.0   
028 - SPINAL PROCEDURES W MCC                        NaN    NaN    NaN   14.0   
029 - SPINAL PROCEDURES W CC OR SPINAL NEUROSTI...   NaN   26.0    NaN   29.0   
030 - SPINAL PROCEDURES W/O CC/MCC                   NaN    NaN    NaN   13.0   
031 - VENTRICULAR SHUNT PROCEDURES W MCC             NaN   11.0   11.0    NaN   
032 - VENTRICULAR SHUNT PROCEDURES W CC              NaN   11.0    NaN   40.0   
033 - VENTRICULAR SHUNT PROCEDURES W/O CC/MCC        NaN   27.0   17.0   34.0   
034 - CAROTID ARTERY STENT PROCEDURE W MCC           NaN    NaN    NaN    NaN   
035 - CAROTID ARTERY STENT PROCEDURE W CC            NaN   14.0   11.0   13.0   
036 - CAROTID ARTERY STENT PROCEDURE W/O CC/MCC      NaN   81.0   16.0   70.0   
037 - EXTRACRANIAL PROCEDURES W MCC                  NaN   23.0   13.0   17.0   
...                                                  ...    ...    ...    ...   
921 - COMPLICATIONS OF TREATMENT W/O CC/MCC          NaN    NaN   11.0    NaN   
923 - OTHER INJURY, POISONING & TOXIC EFFECT DI...   NaN    NaN    NaN    NaN   
927 - EXTENSIVE BURNS OR FULL THICKNESS BURNS W...   NaN    NaN    NaN    NaN   
928 - FULL THICKNESS BURN W SKIN GRAFT OR INHAL...   NaN   45.0    NaN   18.0   
929 - FULL THICKNESS BURN W SKIN GRAFT OR INHAL...   NaN    NaN    NaN    NaN   
934 - FULL THICKNESS BURN W/O SKIN GRFT OR INHA...   NaN    NaN    NaN    NaN   
935 - NON-EXTENSIVE BURNS                            NaN   32.0    NaN   23.0   
940 - O.R. PROC W DIAGNOSES OF OTHER CONTACT W ...   NaN    NaN    NaN    NaN   
945 - REHABILITATION W CC/MCC                        NaN    NaN    NaN    NaN   
946 - REHABILITATION W/O CC/MCC                      NaN    NaN    NaN    NaN   
947 - SIGNS & SYMPTOMS W MCC                         NaN   53.0   11.0   16.0   
948 - SIGNS & SYMPTOMS W/O MCC                      43.0  679.0  404.0  353.0   
949 - AFTERCARE W CC/MCC                             NaN    NaN    NaN    NaN   
951 - OTHER FACTORS INFLUENCING HEALTH STATUS        NaN    NaN    NaN    NaN   
956 - LIMB REATTACHMENT, HIP & FEMUR PROC FOR M...   NaN   36.0   12.0   14.0   
957 - OTHER O.R. PROCEDURES FOR MULTIPLE SIGNIF...   NaN   36.0    NaN    NaN   
958 - OTHER O.R. PROCEDURES FOR

### Aside: lets quick check out what are the most frequent surgeries

In [28]:
# for our map, we are going to want to 
# normalize the discharges or each surgery 
# for each 
# state by the total discharges across all 
# states for a particular type of surger
#  lets add this to our total_discharges DF
total_discharges["Total"] = total_discharges.sum(axis = 1)
total_discharges["Total"].head() # just look at the first few

DRG Definition
001 - HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SYSTEM W MCC                2990.0
002 - HEART TRANSPLANT OR IMPLANT OF HEART ASSIST SYSTEM W/O MCC                46.0
003 - ECMO OR TRACH W MV 96+ HRS OR PDX EXC FACE, MOUTH & NECK W MAJ O.R.    23974.0
004 - TRACH W MV 96+ HRS OR PDX EXC FACE, MOUTH & NECK W/O MAJ O.R.          23548.0
005 - LIVER TRANSPLANT W MCC OR INTESTINAL TRANSPLANT                         1482.0
Name: Total, dtype: float64

In [30]:
# finally, lets check out the most often
#  performed surgery across all states

# we can do this by sorting our DF by this total we just
# calculated:
total_discharges.sort_values(by = "Total", 
                             ascending=False, 
                             inplace = True)

# now lets just look at the first few of our 
#  sorted array
total_discharges.head()

# so, from this we see that joint replacement
#  or reattachment of a lower extremeity is 
#  the most likely surgery (in number of discharges)
# followed by surgeries for sepsis and then heart failure

Provider State                                         AK      AL      AR  \
DRG Definition                                                              
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  855.0  9146.0  5692.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  452.0  6066.0  5187.0   
291 - HEART FAILURE & SHOCK W MCC                   110.0  3894.0  2143.0   
292 - HEART FAILURE & SHOCK W CC                    166.0  4131.0  2382.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  182.0  4920.0  2462.0   

Provider State                                           AZ       CA      CO  \
DRG Definition                                                                 
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  10472.0  32930.0  7793.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...   6914.0  45434.0  4400.0   
291 - HEART FAILURE & SHOCK W MCC                    2252.0  14894.0  1273.0   
292 - HEART FAILURE & SHOCK W CC                     2092.0  11654.0  1341.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...   3050.0  12358.0  1728.0   

Provider State                                          CT      DC      DE  \
DRG Definition                                                               
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  5689.0  1247.0  2119.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  6390.0   643.0  1556.0   
291 - HEART FAILURE & SHOCK W MCC                   2806.0   529.0  1019.0   
292 - HEART FAILURE & SHOCK W CC                    2714.0   902.0   936.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  2723.0   556.0   782.0   

Provider State                                           FL  ...       TN  \
DRG Definition                                               ...            
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  31086.0  ...  11133.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  25209.0  ...  11295.0   
291 - HEART FAILURE & SHOCK W MCC                   14923.0  ...   5285.0   
292 - HEART FAILURE & SHOCK W CC                    14274.0  ...   4899.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  20322.0  ...   4681.0   

Provider State                                           TX      UT       VA  \
DRG Definition                                                                 
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  29410.0  4455.0  13923.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  30595.0  2780.0  15119.0   
291 - HEART FAILURE & SHOCK W MCC                   13718.0   500.0   6815.0   
292 - HEART FAILURE & SHOCK W CC                    13047.0   548.0   5863.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  12692.0   492.0   4884.0   

Provider State                                         VT       WA      WI  \
DRG Definition                                                               
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  766.0  10027.0  9482.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  739.0  10146.0  6712.0   
291 - HEART FAILURE & SHOCK W MCC                   303.0   3557.0  3028.0   
292 - HEART FAILURE & SHOCK W CC                    318.0   2900.0  3175.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  249.0   2435.0  2582.0   

Provider State                                          WV     WY     Total  
DRG Definition                                                               
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  2925.0  651.0  916518.0  
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  3427.0  474.0  877194.0  
291 - HEART FAILURE & SHOCK W MCC                   1535.0  161.0  397778.0  
292 - HEART FAILURE & SHOCK W CC                    1749.0  212.0  385836.0  
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  1632.0  168.0  380750.0  

[5 rows x 52 columns]

In [33]:
# neat.  We won't need these for plotting, so we can remove our
# total column we just calculated
del total_discharges["Total"]
total_discharges.head()
# now we see that we are back to just states & surgeries
#  *but* our sorting is still by the total that we 
# previously calculated.
# spiffy!

Provider State                                         AK      AL      AR  \
DRG Definition                                                              
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  855.0  9146.0  5692.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  452.0  6066.0  5187.0   
291 - HEART FAILURE & SHOCK W MCC                   110.0  3894.0  2143.0   
292 - HEART FAILURE & SHOCK W CC                    166.0  4131.0  2382.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  182.0  4920.0  2462.0   

Provider State                                           AZ       CA      CO  \
DRG Definition                                                                 
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  10472.0  32930.0  7793.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...   6914.0  45434.0  4400.0   
291 - HEART FAILURE & SHOCK W MCC                    2252.0  14894.0  1273.0   
292 - HEART FAILURE & SHOCK W CC                     2092.0  11654.0  1341.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...   3050.0  12358.0  1728.0   

Provider State                                          CT      DC      DE  \
DRG Definition                                                               
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  5689.0  1247.0  2119.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  6390.0   643.0  1556.0   
291 - HEART FAILURE & SHOCK W MCC                   2806.0   529.0  1019.0   
292 - HEART FAILURE & SHOCK W CC                    2714.0   902.0   936.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  2723.0   556.0   782.0   

Provider State                                           FL  ...      SD  \
DRG Definition                                               ...           
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  31086.0  ...  3200.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  25209.0  ...  1574.0   
291 - HEART FAILURE & SHOCK W MCC                   14923.0  ...   540.0   
292 - HEART FAILURE & SHOCK W CC                    14274.0  ...   511.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  20322.0  ...   436.0   

Provider State                                           TN       TX      UT  \
DRG Definition                                                                 
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  11133.0  29410.0  4455.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  11295.0  30595.0  2780.0   
291 - HEART FAILURE & SHOCK W MCC                    5285.0  13718.0   500.0   
292 - HEART FAILURE & SHOCK W CC                     4899.0  13047.0   548.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...   4681.0  12692.0   492.0   

Provider State                                           VA     VT       WA  \
DRG Definition                                                                
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  13923.0  766.0  10027.0   
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  15119.0  739.0  10146.0   
291 - HEART FAILURE & SHOCK W MCC                    6815.0  303.0   3557.0   
292 - HEART FAILURE & SHOCK W CC                     5863.0  318.0   2900.0   
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...   4884.0  249.0   2435.0   

Provider State                                          WI      WV     WY  
DRG Definition                                                             
470 - MAJOR JOINT REPLACEMENT OR REATTACHMENT O...  9482.0  2925.0  651.0  
871 - SEPTICEMIA OR SEVERE SEPSIS W/O MV 96+ HO...  6712.0  3427.0  474.0  
291 - HEART FAILURE & SHOCK W MCC                   3028.0  1535.0  161.0  
292 - HEART FAILURE & SHOCK W CC                    3175.0  1749.0  212.0  
392 - ESOPHAGITIS, GASTROENT & MISC DIGEST DISO...  2582.0  1632.0  168.0  

[5 rows x 51 columns]

## 1.c: plot data with bqplot

In [40]:
import bqplot
# by default bqplot does not import 
#  all packages, we have to 
#  explicitely import market_map
import bqplot.market_map # for access to market_map

In [55]:
# lets do our usual thing, but with a market map
#  instead of a heat map

# scales:
x_sc, y_sc = bqplot.OrdinalScale(), bqplot.OrdinalScale() # note, just a different way to call things
c_sc = bqplot.ColorScale(scheme="Blues")

# just a color axes for now:
c_ax = bqplot.ColorAxis(scale = c_sc, orientation = 'vertical')

# lets make the market map:

# (1) what should we plot for our color? lets take a look:
total_discharges.iloc[0].values, total_discharges.columns.values
# this is the total discharges for the most 
# popular surgical procedure
# the columns will be states

# (2) lets put this into a map
mmap = bqplot.market_map.MarketMap(color = total_discharges.iloc[0].values, 
                                  names = total_discharges.columns.values,
                                  scales={'color':c_sc}, 
                                   axes=[c_ax])

# (3) ok, but just clicking on things doesn't tell us too much
# lets add a little label to print out the total of the selected
import ipywidgets
label = ipywidgets.Label()
# link to market map
def get_data(change):
    # (3.1)
    #print(change['owner'].selected)
    # (3.2) loop
    v = 0.0 # to store total value
    for s in change['owner'].selected:
        v += total_discharges.iloc[0][total_discharges.iloc[0].index == s].values
    if v > 0: # in case nothing is selected
        # what are we printing?
        l = 'Total discharges of ' + \
        total_discharges.iloc[0].name + \
        ' = ' + str(v[0]) # note: v is by default an array
        label.value = l 
    
mmap.observe(get_data,'selected')
    
#mmap

# (3)
ipywidgets.VBox([label,mmap])

VkJveChjaGlsZHJlbj0oTGFiZWwodmFsdWU9dScnKSwgTWFya2V0TWFwKGF4ZXM9W0NvbG9yQXhpcyhvcmllbnRhdGlvbj0ndmVydGljYWwnLCBzY2FsZT1Db2xvclNjYWxlKHNjaGVtZT11J0LigKY=


## Discussion:
* think back to the map we had last week: we can certainly plot this information with a more geo-realistic map
* what are the pros & cons of each style of map?  What do each highlight?  How are each biased?

## IF we have time: Re-do with other mapping system:

In [148]:
from us_state_abbrev import us_state_abbrev

sc_geo = bqplot.AlbersUSA()
state_data = bqplot.topo_load('map_data/USStatesMap.json')

#(1)
#states_map = bqplot.Map(map_data=state_data, scales={'projection':sc_geo})

#(2)
# library from last time
from states_utils import get_ids_and_names
ids, state_names = get_ids_and_names(states_map)

# color maps
import matplotlib.cm as cm
cmap = cm.Blues

# most popular surgery
popSurg = total_discharges.iloc[0]

# here, we will go through the process of getting colors to plot
#  each state with its similar color to the marketmap above:

#!pip install webcolors
from webcolors import rgb_to_hex
d = {} # empty dict to store colors
for s in states_map.map_data['objects']['subunits']['geometries']:
    if s['properties'] is not None:
        #print(s['properties']['name'], s['id'])
        # match states to abbreviations
        state_abbrev = us_state_abbrev[s['properties']['name']]
        #print(state_abbrev)
        v = popSurg[popSurg.index == state_abbrev].values[0]
        # renorm v to colors and then number of states
        v = (v - popSurg.values.min())/(popSurg.values.max()-popSurg.values.min())
        #print(v, int(cmap(v)[0]), int(cmap(v)[1]), int(cmap(v)[2]))
        # convert to from 0-1 to 0-255 rgbs
        c = [int(cmap(v)[i]*255) for i in range(3)]
        #d[s['id']] = rgb_to_hex([int(cmap(v)[0]*255), int(cmap(v)[1]*255), int(cmap(v)[2]*255)])
        d[s['id']] = rgb_to_hex(c)
    
    
def_tt = bqplot.Tooltip(fields=['name'])
    
states_map = bqplot.Map(map_data=state_data, scales={'projection':sc_geo}, colors = d, tooltip=def_tt)
# add interactions
states_map.interactions = {'click': 'select', 'hover': 'tooltip'}

# (3)
label = ipywidgets.Label()
# link to heat map
def get_data(change):
    v = 0.0 # to store total value
    if change['owner'].selected is not None:
        for s in change['owner'].selected:
            #print(s)
            sn = state_names[s == ids][0]
            state_abbrev = us_state_abbrev[sn]
            v += popSurg[popSurg.index == state_abbrev].values[0]
        if v > 0: # in case nothing is selected
            # what are we printing?
            l = 'Total discharges of ' + \
            popSurg.name + \
            ' = ' + str(v) # note: v is by default an array
            label.value = l 
    
states_map.observe(get_data,'selected')
    
#


fig=bqplot.Figure(marks=[states_map], 
                  title='US States Map Example',
                  fig_margin={'top': 0, 'bottom': 0, 'left': 0, 'right': 0}) # try w/o first and see
#fig
# (3)
ipywidgets.VBox([label,fig])

VkJveChjaGlsZHJlbj0oTGFiZWwodmFsdWU9dScnKSwgRmlndXJlKGZpZ19tYXJnaW49eyd0b3AnOiAwLCAnbGVmdCc6IDAsICdyaWdodCc6IDAsICdib3R0b20nOiAwfSwgbGF5b3V0PUxheW/igKY=


# Activity #2: Networked data


In [150]:
# lets start with some very basic node data
# **copy paste into chat **
node_data = [
    {"label": "Luke Skywalker", "media": "Star Wars", "shape": "rect"},
    {"label": "Jean-Luc Picard", "media": "Star Trek", "shape": "rect"},
    {"label": "Doctor Who", "media": "Doctor Who", "shape": "rect"},
    {"label": "Pikachu", "media": "Detective Pikachu", "shape": "circle"},
]

# we'll use bqplot.Graph to plot these
graph = bqplot.Graph(node_data=node_data,
                    colors = ["red", "red", "red", "red"])

fig = bqplot.Figure(marks = [graph])
fig

# you note I can pick them up and move them around, but they aren't connected in any way
# lets make some connections

RmlndXJlKGZpZ19tYXJnaW49eyd0b3AnOiA2MCwgJ3JpZ2h0JzogNjAsICdib3R0b20nOiA2MCwgJ2xlZnQnOiA2MH0sIGxheW91dD1MYXlvdXQobWluX3dpZHRoPXUnMTI1cHgnKSwgbWFya3PigKY=


In [166]:
node_data = [
    {"label": "Luke Skywalker", "media": "Star Wars", "shape": "rect"},
    {"label": "Jean-Luc Picard", "media": "Star Trek", "shape": "rect"},
    {"label": "Doctor Who", "media": "Doctor Who", "shape": "rect"},
    {"label": "Pikachu", "media": "Detective Pikachu", "shape": "circle"},
]

# lets link the 0th entry (luke skywalker) to both
#  jean-luc picard (1th entry) and pikachu (3rd entry)
link_data = [{'source': 0, 'target': 1}, {'source': 0, 'target':  3}]

graph = bqplot.Graph(node_data=node_data, link_data=link_data, 
                    colors = ["red", "red", "red", "red"])

#(2) we can also play with the springiness of our links:
graph.charge = -300 # setting it to positive makes them want to overlap and is, ingeneral, a lot of fun
# -300 is default

# (3) we can also change the link type:
graph.link_type = 'line' # arc = default, line, slant_line

# (4) highlight link direction, or not
graph.directed = False

fig = bqplot.Figure(marks = [graph])
fig

RmlndXJlKGZpZ19tYXJnaW49eyd0b3AnOiA2MCwgJ3JpZ2h0JzogNjAsICdib3R0b20nOiA2MCwgJ2xlZnQnOiA2MH0sIGxheW91dD1MYXlvdXQobWluX3dpZHRoPXUnMTI1cHgnKSwgbWFya3PigKY=


In [178]:
# we can do all the same things we've done with
# our previous map plots:
# for example, we can add a tooltip:
#(1)
tooltip = bqplot.Tooltip(fields=["media"])
graph = bqplot.Graph(node_data=node_data, link_data=link_data, 
                    colors = ["red", "red", "red", "red"],
                    tooltip=tooltip)

# we can also do interactive things with labels
label = ipywidgets.Label()

# note here that the calling sequence 
# is a little different - instead 
# of "change" we have "obj" and 
# "element"
def printstuff(obj, element):
    # (1.1)
    #print(obj)
    #print(element)
    label.value = 'Media = ' + element['data']['media']
    
graph.on_element_click(printstuff)


fig = bqplot.Figure(marks = [graph])
ipywidgets.VBox([label,fig])

VkJveChjaGlsZHJlbj0oTGFiZWwodmFsdWU9dScnKSwgRmlndXJlKGZpZ19tYXJnaW49eyd0b3AnOiA2MCwgJ3JpZ2h0JzogNjAsICdib3R0b20nOiA2MCwgJ2xlZnQnOiA2MH0sIGxheW91dD3igKY=


In [231]:
G = pd.read_csv('/Users/jillnaiman1/Downloads/facebook_combined.txt',sep=' ', names=['ind1', 'ind2'])
G

ind1  ind2
0         0     1
1         0     2
2         0     3
3         0     4
4         0     5
5         0     6
6         0     7
7         0     8
8         0     9
9         0    10
10        0    11
11        0    12
12        0    13
13        0    14
14        0    15
15        0    16
16        0    17
17        0    18
18        0    19
19        0    20
20        0    21
21        0    22
22        0    23
23        0    24
24        0    25
25        0    26
26        0    27
27        0    28
28        0    29
29        0    30
...     ...   ...
88204  4014  4017
88205  4014  4021
88206  4014  4023
88207  4014  4030
88208  4014  4037
88209  4014  4038
88210  4016  4025
88211  4017  4021
88212  4017  4026
88213  4017  4030
88214  4018  4023
88215  4018  4030
88216  4019  4026
88217  4019  4030
88218  4020  4027
88219  4020  4030
88220  4020  4031
88221  4020  4037
88222  4020  4038
88223  4021  4026
88224  4021  4030
88225  4023  4030
88226  4023  4031
88227  4023  4034
88228  4023  4038
88229  4026  4030
88230  4027  4031
88231  4027  4032
88232  4027  4038
88233  4031  4038

[88234 rows x 2 columns]

In [238]:
# this is a large dataset, lets downsample
nsamples = 100
downSampleMask = np.random.choice(range(len(G)-1), nsamples, replace=False)
network = G.iloc[downSampleMask]
#network = G.iloc[:nsamples]

In [253]:
i=0
ind = np.where(network.iloc[i]["ind2"] == network["ind1"].values)[0]
ind

array([], dtype=int64)

In [222]:
# build the network
node_data = []
link_data = []
for i in range(len(network)):
    node_data.append({"label": str(network.iloc[i]["ind1"])#, "shape": "circle"})
    # we are linking the ith object to another jth object, but we 
    #  gotta figure out with jth object it is
    source_id = i
    ind = np.where(network.iloc[i]["ind2"] == network["ind1"].values)[0]
    # here is something tricky - since we downsampled, we have to make sure this
    #  number is actually inthere
    #if len(ind) > 0: # no issue
    #    ind = ind[0]
    #    link_data.append({'source': source_id, 'target': ind})
    #else: # other wise, we gotta add it
    #    node_data.append({"label": str(network.iloc[i]["ind2"]), "shape": "circle"})
        
#node_data

In [257]:
# plot
#graph = bqplot.Graph(node_data=node_data)#, link_data = link_data)
graph = bqplot.Graph(x=G['ind1'],y=G['ind2'])

fig = bqplot.Figure(marks = [graph])
fig


RmlndXJlKGZpZ19tYXJnaW49eyd0b3AnOiA2MCwgJ3JpZ2h0JzogNjAsICdib3R0b20nOiA2MCwgJ2xlZnQnOiA2MH0sIGxheW91dD1MYXlvdXQobWluX3dpZHRoPXUnMTI1cHgnKSwgbWFya3PigKY=


In [179]:
!git clone https://github.com/jcatw/snap-facebook.git
    

Cloning into 'snap-facebook'...
remote: Enumerating objects: 90, done.
remote: Total 90 (delta 0), reused 0 (delta 0), pack-reused 90
Unpacking objects: 100% (90/90), done.


In [182]:
from sys import path
path.append('./snap-facebook/')

import facebook

# load the network
facebook.load_network()

print facebook.network.order()
print facebook.network.size()

# 0: feature not present for this user
# 1: user does not have this feature
# 2: user does have this feature

# look at the features of the whole network
print facebook.feature_matrix()

4039
88234
[0. 0. 0. ... 0. 0. 0.]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [197]:
facebook.network.q


{'features': array([0., 0., 0., ..., 0., 0., 0.])}